### ISSUE TITLE
Error when using pYAAPT for pitch tracking

### ISSUE THREAD

**Issue by ahmed-fau** [bjbschmitt/AMFM_decompy#12]
Hi,

I am using pYAAPT to process multiple speech files, each has 16320 samples at sampling rate = 16kHz with the following config:
`pitch = pYAAPT.yaapt(signal, **{'f0_min' : 50.0, 'frame_length' : 20.0, 'tda_frame_length' : 20.0} )`

However, I get the following error about the time domain frame length:

`AssertionError: ERROR: Negative index in the cross correlation calculation of the pYAAPT time domain analysis. Please try to increase the value of the "tda_frame_length" parameter.`

I don't want to increase the time domain frame length to keep the time resolution high enough (e.g. 20ms). Is there any workaround I can do instead?

Thanks in advance!

**Comment by bjbschmitt** [comment]
Since I received no feedback from this topic. I will close i.t
