### ISSUE TITLE
TypeError: pcm2float() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by richardhemphill** [bjbschmitt/AMFM_decompy#8]
The parameter name of 'dtype' in the [call](https://github.com/bjbschmitt/AMFM_decompy/blob/master/amfm_decompy/basic_tools.py#L39) to [pcm2float()](https://github.com/bjbschmitt/AMFM_decompy/blob/master/amfm_decompy/basic_tools.py#L90 ) does not match the actual parameter name of 'output_dtype'.

https://github.com/bjbschmitt/AMFM_decompy/blob/9921baa2d6208de7a61b0fabb2da2e9fe8ed7bc7/amfm_decompy/basic_tools.py#L39

**Comment by bjbschmitt** [comment]
Hi Richard, thank you for your feedback. Could you please send me the wav that caused the issue, so that I can implement the proper fix?

**Comment by richardhemphill** [comment]
http://www.ws.binghamton.edu/zahorian/yaapt/yaapt.zip

Within zip, 
YAPPT_v4.0\sample\f1nw0000pes_short.wav

import amfm_decompy.basic_tools as basic
signal = basic.SignalObj('f1nw0000pes_short.wav')

**Comment by bjbschmitt** [comment]
Ok, I have tested 

`import amfm_decompy.basic_tools as basic`
`signal = basic.SignalObj('f1nw0000pes_short.wav')`

and everything went fine. Could you please send a print screen from your error message? Maybe it can help me to find out why it is not working in your computer.

**Comment by richardhemphill** [comment]
See attached.

**Comment by bjbschmitt** [comment]
Ok, I understand now your point, the name of the variable is wrong. I will fix it then and also make some improvements. 

The only thing strange is the fact that this bug remained unnoticed for so much time. As I mentioned, my computer ignores it and probably employs the [default value for output_dtype](https://github.com/bjbschmitt/AMFM_decompy/blob/9921baa2d6208de7a61b0fabb2da2e9fe8ed7bc7/amfm_decompy/basic_tools.py#L90). Maybe it is something related with the installed Python/Conda version, or something like that.

**Comment by bjbschmitt** [comment]
Hi Richard, sorry about the delay. I have fixed the bug and uploaded the new AMFM_decompy 1.0.9 version to both PyPi and github repositories. The documentation has also been updated as well. 

Please upgrade your AMFM_decompy version through pip and check if the problem has in fact been solved.

**Comment by richardhemphill** [comment]
Latest version works.  Thanks.
