### ISSUE TITLE
Frame Length of 3 Causes TypeError: m > k must hold

### ISSUE THREAD

**Issue by richardhemphill** [bjbschmitt/AMFM_decompy#9]
https://github.com/bjbschmitt/AMFM_decompy/blob/4723225ce4e815a406606d84c364f879fa54e131/amfm_decompy/pYAAPT.py#L236

I believe that the code should check for length greater than 3.
`elif interp_tech is 'spline' and len(frame) > 3:`

If the size of the `voiced_frames` after splitting to the edges results in a `frame` of length 3, then the `scipy_interp.splprep` call will result in `TypeError: m > k must hold`.  The reason is because the degree of the spline (i.e. k) defaults to 3 and length of `samp_values[frame]` is also 3.

Ref: https://github.com/scipy/scipy/blob/8675d6e3bb84c813b4ab9bbad7a493e3c51d101c/scipy/interpolate/_fitpack_impl.py#L263

**Comment by bjbschmitt** [comment]
Hi Richard. I'll take a look on this, thank you for pointing this issue.

**Comment by bjbschmitt** [comment]
Hi Richard, sorry about delay. I'm in the middle of a business trip, so it was a bit difficult to find some free time to make the corrections and update the package. 

Anyway, the new version is already available online in both github and pypi. 

Thank you again for the feedback!
